### ISSUE TITLE
Possible typos in documentation

### ISSUE THREAD

**Issue by gazzatav** [Saswatm123/Compile-Time-Equations-Handler#4]
In the documentation:
> Crucial: any exponentiation must be inside parentheses due to natural C++ operator precedence putting ^ last. That means that the formula
> 
>     G = (1 - v^2 / c^2 )^(1.0/2.0) ) 
> 
> is written as:
> 
>     G == (1 - (v^2) / (c^2) )^(1.0/2.0)
There seems to be an extra parenthesis at the end of the first formula.  In the 'written as:' line a boolean '==' operator is used.  Is this a typo or a trick to evaluate the expression?

**Comment by Saswatm123** [comment]
The '==' is the correct operator to evaluate the expression, there is no typo. I used the single '=' in the top equation just to write how that might be the 'normal' way to think about an equation (as if we were writing it by hand). The bottom one is the semantically correct one that works with the program. Thanks for giving it a read, I might end up changing that anyway for clarity.
